jobs:
  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: install AWS CLI
          command: sudo apt-get update
            sudo apt-get install -y python-pip python-dev
            sudo pip install awscli
      - run: npm install && npm run build
      - run: aws s3 sync ./build s3://phb-dashboard

workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_deploy
